---

# Apply common configuration to all hosts (only add SSH public key ftm)
- hosts: all
  roles:
  - common

# Remove ports 80 and 443 on Synology webserver
#- hosts: nas
#  become: yes
#roles:
#- dsm_nginx

# Configure NUT client on Proxmox cluster
- hosts: proxmox
  become: yes
  roles:
  - pve
  - nut
