---
# Minimal post-installation for Proxmox VE

- name: Disable the Enterprise repositories
  replace:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    backup: yes
    regexp: '^deb(.+)$'
    replace: '# deb\1'

- name: Set up the No-Subscription repository
  lineinfile:
    path: /etc/apt/sources.list
    backup: yes
    line: deb http://download.proxmox.com/debian/pve buster pve-no-subscription

- name: Remove the annoying subscription popup
  replace:
    path: /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js
    backup: yes
    regexp: "Ext.Msg.show"
    after: ".data.status"
    before: "No valid subscription"
    replace: "void"
  notify: restart pveproxy
