---
# Configure NUT client

- name: Get latest nut package
  apt:
    name: nut
    state: latest

- name: Edit /etc/nut/nut.conf
  lineinfile:
    path: /etc/nut/nut.conf
    backup: yes
    regexp: '^MODE='
    line: MODE=netclient
  notify: restart nut-client

- name: Edit /etc/nut/upsmon.conf
  lineinfile:
    path: /etc/nut/upsmon.conf
    backup: yes
    regexp: '^MONITOR'
    insertafter: '^# MONITOR'
    line: MONITOR {{ ups_name }}@{{ nut_server_ip }} 1 {{ nut_user }} {{ nut_password }} slave
  notify: restart nut-client

- name: Ensure nut monitoring is running
  service:
    name: nut-client
    state: started
    enabled: yes

- name: Check UPS status
  shell: upsc {{ ups_name }}@{{ nut_server_ip }}
  register: ups_status

- name: UPS STATUS
  debug:
    var: ups_status.stdout_lines