---
# Apply common configuration to all hosts (only add SSH public key ftm)

- name: Change user home directory rights to 755 (for Synology NAS)
  file:
    path: /volume1/homes/{{ ansible_user }}
    state: directory
    mode: '0755'
  when: inventory_hostname in groups['nas']

- name: Add my SSH key
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ lookup('file', pubkey_file) }}"
    exclusive: yes
